server:
  port: 9002

spring:
  application:
    name: msb-weather-data-eureka
  redis:
    host: 192.168.121.181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: msb-weather-data-eureka #每个项目唯一
    prefer-ip-address: true     #访问路径可以显示IP地址


# 天气数据API微服务  从redis中获取天气信息
# http://localhost:9002/weather/cityId/101280601
