server:
  port: 9006


spring:
  application:
    name: msb-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suzhenglong/spring-cloud-config-repo      # 配置Git仓库的地址
          search-paths: config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: msb-weather-config-server #每个项目唯一
    prefer-ip-address: true     #访问路径可以显示IP地址

# http://localhost:9006/msb-weather-config-client/dev