server:
  port: 9001

spring:
  application:
    name: msb-weather-collection-eureka-fegin
  redis:
    host: 192.168.121.181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: msb-weather-collection-eureka-fegin #每个项目唯一
    prefer-ip-address: true     #访问路径可以显示IP地址

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

# 天气数据采集微服务
# 测试
# 查看redis中的数据