server:
  port: 9004


spring:
  application:
    name: msb-weather-city-eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: msb-weather-city-eureka #每个项目唯一
    prefer-ip-address: true     #访问路径可以显示IP地址

# 城市数据API微服务
# http://localhost:9004/cities